model:
  replicaCount: 1
  image:
    repository: "yourdockerusername/ocr-model-service"
    tag: "latest"
    pullPolicy: IfNotPresent
  service:
    type: NodePort
    port: 8080
    nodePort: 32000

gateway:
  replicaCount: 1
  image:
    repository: "yourdockerusername/ocr-api-gateway"
    tag: "latest"
    pullPolicy: IfNotPresent
  service:
    type: NodePort
    port: 8001
    nodePort: 32001
