model:
  replicaCount: 1
  image:
    repository: "yourdockerusername/ocr-model-service"
    tag: "latest"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8080

gateway:
  replicaCount: 1
  image:
    repository: "yourdockerusername/ocr-api-gateway"
    tag: "latest"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8001
