apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ocr-services
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/YaishRiaz/DevOpsEngineer-Assignment.git'
    targetRevision: master
    path: ocr-services  
    helm:
      valueFiles:
      - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
