apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ocr-services.fullname" . }}-gateway
  labels:
    app: {{ include "ocr-services.name" . }}
    component: gateway
spec:
  replicas: {{ .Values.gateway.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "ocr-services.fullname" . }}-gateway
  template:
    metadata:
      labels:
        app: {{ include "ocr-services.fullname" . }}-gateway
    spec:
      containers:
      - name: gateway
        image: "{{ .Values.gateway.image.repository }}:{{ .Values.gateway.image.tag }}"
        imagePullPolicy: {{ .Values.gateway.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.gateway.service.port }}
