apiVersion: v1
kind: Service
metadata:
  name: {{ include "ocr-services.fullname" . }}-gateway
spec:
  type: {{ .Values.gateway.service.type }}
  ports:
  - port: {{ .Values.gateway.service.port }}
    targetPort: {{ .Values.gateway.service.port }}
  selector:
    app: {{ include "ocr-services.fullname" . }}-gateway
